NAME		= 	parser

SRCS 		=	main.cpp ConfigParser.cpp VirtualServer.cpp utils.cpp ServersInterface.cpp CommonServers.cpp Location.cpp

GO			=	clang++ -std=c++98 -Wall -Wextra -Werror #-fsanitize=address -g3

all:	$(NAME)

$(NAME): $(SRCS)
		@$(GO) -o $(NAME) $(SRCS)

clean:
	@rm -rf $(OBJ)

fclean: clean
	@rm -rf $(NAME)

re: fclean all

.PHONY: clean fclean re all
